# # Convergence vs. Delay Parameter B
#
# This experiment demonstrates how the maximum delay parameter ``B`` affects
# convergence of asynchronous sheaf diffusion. Each agent's update and
# broadcast periods are sampled from a Gaussian mixture with mean proportional
# to ``B``, so larger ``B`` means longer delays between updates.
#
# We run the same diffusion on three graph topologies — a 4-regular graph,
# an Erdős–Rényi random graph, and a star graph — and sweep ``B \in \{1, 10, 50, 100, 200\}``.
#
# **Data source:** Pre-generated by `docs/scripts/acc26_experiments.jl`.
# To regenerate, run:
# ```julia
# julia --project=docs docs/scripts/acc26_experiments.jl
# ```

using CellularSheaves
using Plots
using LaTeXStrings

const data_root = joinpath(@__DIR__, "../../../data/asynch/converge_vs_delay")

subsample(v, n=2000) = v[1:max(1, length(v) ÷ n):end]

Bs = [1, 10, 50, 100, 200]
labels = ["B=1", "B=10", "B=50", "B=100", "B=200"]
topologies = ["regular_graph", "er_graph", "complete_graph"]
topology_titles = ["4-Regular", "Erdős–Rényi", "Star"]

# ## Energy loss across graph topologies

loss_plots = map(zip(topologies, topology_titles)) do (top, title)
    plt = empty_experiment_plot(; title=title)
    for (i, (B, lab)) in enumerate(zip(Bs, labels))
        path = joinpath(data_root, top, "loss$i.csv")
        isfile(path) || continue
        loss = subsample(vec(load_trajectory(path)))
        plot_log_loss_curve!(plt, loss, lab)
    end
    plt
end

# ## Relative error across graph topologies

error_plots = map(zip(topologies, topology_titles)) do (top, title)
    plt = empty_experiment_plot(; xlabel=L"\mathrm{Iteration},\quad t")
    for (i, (B, lab)) in enumerate(zip(Bs, labels))
        path = joinpath(data_root, top, "error$i.csv")
        isfile(path) || continue
        err = subsample(vec(load_trajectory(path)))
        plot_log_loss_curve!(plt, err, lab)
    end
    plt
end

l = @layout [a b c; d e f]
plot(
    loss_plots..., error_plots...,
    layout=l,
    size=(1900, 700),
    ylabel=[L"f(\mathbf{x})" "" "" L"\|\mathbf{x}-\mathbf{x}^*\|/\|\mathbf{x}^*\|" "" ""],
    legend=:topright,
)
