# # Convergence vs. Delay Parameter B
#
# This experiment demonstrates how the maximum delay parameter ``B`` affects
# convergence of asynchronous sheaf diffusion. Each agent's update and
# broadcast periods are sampled from a Gaussian mixture with mean proportional
# to ``B``, so larger ``B`` means longer delays between updates.
#
# We run the same diffusion on three graph topologies — a 4-regular graph,
# an Erdős–Rényi random graph, and a star graph — and sweep ``B \in \{1, 10, 50, 100, 200\}``.
#
# **Data source:** Pre-generated by `docs/scripts/acc26_experiments.jl`.
# To regenerate the data and re-render the figure, run:
# ```julia
# julia --project=docs docs/scripts/acc26_experiments.jl
# julia --project=docs docs/scripts/generate_figures.jl
# ```

# ## Energy loss and relative error across graph topologies
#
# Top row: energy ``f(\mathbf{x}(t))`` for each topology.
# Bottom row: relative error ``\|\mathbf{x}(t)-\mathbf{x}^*\|/\|\mathbf{x}^*\|``.

# ![Convergence vs. Delay](../../assets/figures/asynch/convergence_vs_delay.svg)
