# # Restriction Map Type Comparison
#
# The structure of a sheaf's restriction maps determines how information is
# aggregated across edges. This experiment compares three sheaf types on a
# 4-regular graph with ``n=20`` agents and stalk dimension 4, all diffused with
# the same mixture-model asynchronous schedule (``B=200``):
#
# - **Constant sheaf**: identity restriction maps — each vertex sees the same
#   information at both endpoints of each edge. Global sections are constant signals.
# - **Random vector bundle**: semi-orthogonal restriction maps — models a
#   principal bundle where the fiber is rotated across each edge.
# - **Matrix-weighted**: restriction maps derived from random PD/PSD matrices —
#   models asymmetric information blending, relevant to network opinion dynamics.
#
# For each sheaf type we plot energy ``f(\mathbf{x}(t))``, relative error
# ``\|\mathbf{x}(t) - \mathbf{x}^*\| / \|\mathbf{x}^*\|``, and orthogonal
# projection error ``\|\mathbf{x}(t) - \Pi_\Gamma[\mathbf{x}(0)]\| / \|\Pi_\Gamma[\mathbf{x}(0)]\|``.
#
# **Data source:** Pre-generated by `docs/scripts/acc26_experiments.jl`.
# To regenerate the data and re-render the figure, run:
# ```julia
# julia --project=docs docs/scripts/acc26_experiments.jl
# julia --project=docs docs/scripts/generate_figures.jl
# ```

# ![Restriction Map Type Comparison](../../assets/figures/asynch/restriction_map_comparison.svg)
