# # Step Size Comparison: Optimal vs. Conservative
#
# This experiment compares three step size strategies for asynchronous sheaf
# diffusion on a 4-regular graph with semi-orthogonal restriction maps:
#
# - **Synchronous ``1/K``**: the optimal synchronous step size, applied to the
#   synchronous gradient descent baseline.
# - **Asynchronous ``1/K``**: the synchronous-optimal step size applied to the
#   asynchronous algorithm (ignoring delay). Converges in practice for moderate ``B``.
# - **Conservative ``0.1/K``**: a smaller step that is provably safe even with
#   large delay, at the cost of slower convergence.
#
# **Data source:** Pre-generated by `docs/scripts/acc26_experiments.jl`.
# To regenerate the data and re-render the figure, run:
# ```julia
# julia --project=docs docs/scripts/acc26_experiments.jl
# julia --project=docs docs/scripts/generate_figures.jl
# ```

# ![Step Size Comparison](../../assets/figures/asynch/step_size_comparison.svg)
